Rewrite of init script

diff --git a/dot_zfunc/doinit b/dot_zfunc/doinit
--- a/dot_zfunc/doinit
+++ b/dot_zfunc/doinit
@@ -1,99 +1,164 @@
 
-sudo apt update && sudo apt upgrade -y
+# Global settings
 
-sudo apt install \
-ncdu htop tldr fd-find bat fzf exuberant-ctags \
-build-essential cmake pigz unzip pkg-config ninja-build gettext \
-libtool libtool-bin autoconf automake curl doxygen \
-bspwm sxhkd picom thunar rofi feh ranger physlock \
-maim imagemagick \
-papirus-icon-theme \
-mpd mpc ncmpcpp \
-python3-pip python3-sphinx python3-packaging python3-xcbgen \
-clangd \
-webp-pixbuf-loader xcb-proto \
-libnotify-dev libuv1-dev libcairo2-dev libxcb1-dev libxcb-util0-dev \
-libxcb-randr0-dev libxcb-composite0-dev libxcb-image0-dev libxcb-ewmh-dev \
-libxcb-icccm4-dev libxcb-xkb-dev libxcb-cursor-dev libasound2-dev libpulse-dev \
-libjsoncpp-dev libmpdclient-dev libcurl4-openssl-dev libnl-genl-3-dev \
-libjpeg-dev libxkbcommon-dev libxcb-xrm-dev libxcb-xinerama0-dev libx11-xcb-dev \
-libev-dev libfontconfig1-dev libpam0g-dev \
--y
+# Colors
+BLACK=$(tput setaf 0)
+RED=$(tput setaf 1)
+GREEN=$(tput setaf 2)
+YELLOW=$(tput setaf 3)
+LIME_YELLOW=$(tput setaf 190)
+POWDER_BLUE=$(tput setaf 153)
+BLUE=$(tput setaf 4)
+MAGENTA=$(tput setaf 5)
+CYAN=$(tput setaf 6)
+WHITE=$(tput setaf 7)
+BRIGHT=$(tput bold)
+NORMAL=$(tput sgr0)
+BLINK=$(tput blink)
+REVERSE=$(tput smso)
+UNDERLINE=$(tput smul)
 
-# Change shell to ZSH
-chsh -s $(which zsh)
+# Let's get it started!
+setup() {
+    printf "\n\n%s\n\n" "${MAGENTA}${BRIGHT}Getting Started${NORMAL}"
+    # Make temp scratch dir
+    scratch=$(mktemp -d -t tmp.XXXXXXXXXX)
+    doupdate
 
-# Pipe install node into bash and pass -y
-curl -sL install-node.now.sh/lts | sudo bash -s -- -y
+    # Change shell to ZSH
+    chsh -s $(which zsh)
+}
 
-curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
+# Install needed packages via apt
+apt_install() {
+    printf "\n\n%s\n\n" "${MAGENTA}${BRIGHT}Installing required packages and libraries${NORMAL}"
+    sudo apt install --ignore-missing $(< ${HOME}/.config/packages.list) -y
+}
 
-source $HOME/.cargo/env
+git_setup() {
+    printf "\n\n%s\n\n" "${MAGENTA}${BRIGHT}Setting up git with user.name and user.email${NORMAL}"
+    read "git_user?Git user.name: "
+    read "git_email?Git user.email: "
+    printf "\n%s" "${BLUE}Doing git setup, user.name = ${git_user}, user.email = ${git_email}${NORMAL}"
+    git config --global user.email "${git_email}"
+    git config --global user.name "${git_user}"
+}
 
-cargo install exa procs bottom ripgrep tealdeer alacritty
-cargo install zoxide --locked
+install_programming_langauges() {
+    printf "\n\n%s\n\n" "${MAGENTA}${BRIGHT}Installing programming langauges${NORMAL}"
 
-# Clone, build, and install eww
-git clone https://github.com/elkowar/eww
-cd eww
-cargo build --release
-sudo cp ~/eww/target/release/eww /usr/bin/
-cd
+    # Rust
+    printf "${BLUE}Installing Rust\n${NORMAL}"
+    curl --proto '=https' --tlsv1.2 --silent --show-error --fail https://sh.rustup.rs | sh -s -- -y
+    source $HOME/.cargo/env
 
-# Clone Neovim, INSTALL IT!
-export CMAKE_BUILD_TYPE=Release
-git clone https://github.com/neovim/neovim.git
-cd neovim
-make
-sudo make install
-cd
+    # Node.js
+    printf "${BLUE}Installing node.js\n${NORMAL}"
+    # Pipe install node into bash and pass -y
+    curl --silent --location install-node.now.sh/lts | sudo bash -s -- -y
+}
 
-# Clone Dunst, make, and install
-git clone https://github.com/dunst-project/dunst.git
-cd dunst
-make
-sudo make install
-cd
+cargo_install() {
+    printf "\n\n%s\n\n" "${MAGENTA}${BRIGHT}Installing cool stuff via Cargo${NORMAL}"
+    cargo install $(< ${HOME}/.config/cargo.list)
+}
 
-# Clone polybar, build and install
-git clone --recursive https://github.com/polybar/polybar
-cd polybar
-mkdir build
-cd build
-cmake ..
-make -j$(nproc)
-sudo make install
+git_clone() {
+    git_repo_dir=$(echo ${git_repo} | cut -d '/' -f 5 | cut -d '.' -f 1)
+    git clone --recurse-submodules ${git_repo//[$'\t\r\n']} ${scratch}/${git_repo_dir}
+}
 
-# Clone i3lock color, build, and install
-git clone https://github.com/Raymo111/i3lock-color.git
-cd i3lock-color
-./install-i3lock-color.sh
-cd
+make_install_source() {
+    export CMAKE_BUILD_TYPE=Release
+    
+    while IFS="" read -r git_repo || [ -n "$git_repo" ]
+    do
+        printf "%s\n" "${BLUE}Cloning ${git_repo} and make installing${NORMAL}"
+        git_clone
+        make --directory=${scratch}/${git_repo_dir}
+        sudo make --directory=${scratch}/${git_repo_dir} install
+    done < ${HOME}/.config/make.list
+}
 
-tldr -u
+cargo_build_source() {
 
-# Install betterlockscreen
-wget https://raw.githubusercontent.com/betterlockscreen/betterlockscreen/main/install.sh -O - -q | sudo bash -s system
+    while IFS="" read -r git_repo || [ -n "$git_repo" ]
+    do
+        printf "%s\n" "${BLUE}Cloning ${git_repo} and building with Cargo${NORMAL}"
+        git_clone
+        cd ${scratch}/${git_repo_dir}
+        cargo build --release
+        sudo cp ${scratch}/${git_repo_dir}/target/release/${git_repo_dir} /usr/bin/
+    done < ${HOME}/.config/cargo_build.list
+}
 
-# Run neovim in headless mode to update and compile packer, and add Coc languages
+cmake_install_source() {
 
-# Use sed to change chezmoi git to use SSH instead of https
-sed -i 's/https:\/\//git@/' ~/.local/share/chezmoi/.git/config
-sed -i 's/m\/t/m:t/' ~/.local/share/chezmoi/.git/config
+    while IFS="" read -r git_repo || [ -n "$git_repo" ]
+    do
+        printf "%s\n" "${BLUE}Cloning ${git_repo} and building with Cmake${NORMAL}"
+        git_clone
+        mkdir ${scratch}/${git_repo_dir}/build
+        cd ${scratch}/${git_repo_dir}/build
+        cmake ..
+        make
+        sudo make install
+    done < ${HOME}/.config/cmake_build.list
+}
 
-# Move chezmoi into a more accesible place.
-sudo cp ~/bin/chezmoi /usr/bin/
+weird_installs() {
 
-pip install pynvim
+    printf "\n\n%s\n\n" "${MAGENTA}${BRIGHT}Installing weird ones${NORMAL}"
+    # Clone i3lock color, build, and install
+    git_repo=https://github.com/Raymo111/i3lock-color.git
+    git_clone
+    cd ${scratch}/${git_repo_dir}
+    ./install-i3lock-color.sh
 
-doupdate
+    # Install betterlockscreen
+    cd ${scratch}
+    wget \
+    https://raw.githubusercontent.com/betterlockscreen/betterlockscreen/main/install.sh \
+    -O - -q | sudo bash -s system
+
+    cd
+
+}
+
+final_setup() {
+    # Use sed to change chezmoi git to use SSH instead of https
+    printf "\n\n%s\n\n" "${BLUE}Reconfiguring and moving chezmoi${NORMAL}"
+    sed -i 's/https:\/\//git@/' ~/.local/share/chezmoi/.git/config
+    sed -i 's/m\/t/m:t/' ~/.local/share/chezmoi/.git/config
+
+    # Move chezmoi into a more accesible place.
+    sudo cp ~/bin/chezmoi /usr/bin/
+
+    tldr --update
+
+    pip install pynvim
+
+    # Run neovim in headless mode to update and compile packer, and add Coc languages
+}
 
 # Cleanup
-rm -rf ~/bin
-rm -rf ~/neovim
-rm -rf ~/eww
-rm -rf ~/dunst
-rm -rf ~/polybar
-rm -rf ~/i3lock-color
+finish() {
+    rm --recursive --force ${scratch}
+}
 
-echo "Don't forget to install language servers for CoC and run Packer!"
+#echo "Don't forget to install language servers for CoC and run Packer!"
+# NEW SCRIPT START HERE
+setup
+apt_install
+git_setup
+install_programming_langauges
+cargo_install
+
+make_install_source
+cmake_install_source
+cargo_build_source
+weird_installs
+
+final_setup
+
+trap finish EXIT
